// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package presentation

import (
	"github.com/heyjun3/dforget/backend/config"
	"github.com/heyjun3/dforget/backend/presentation/auth"
	"net/http"
)

// Injectors from wire.go:

func InitializeOIDCHandler(conf server.Config) *auth.OIDCHandler {
	httpClient := provideHttpClient()
	oidcHandler := auth.NewOIDCHandler(conf, httpClient)
	return oidcHandler
}

// wire.go:

func provideHttpClient() auth.HttpClient {
	return &http.Client{}
}
