// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package chat

import (
	chat3 "github.com/heyjun3/dforget/backend/app/chat"
	chat2 "github.com/heyjun3/dforget/backend/domain/chat"
	"github.com/heyjun3/dforget/backend/infra/chat"
	"github.com/uptrace/bun"
)

// Injectors from wire.go:

func InitChatHandler(db *bun.DB) *ChatServiceHandler {
	chatRepository := chat.NewChatRepository(db)
	createRoomService := chat2.NewCreateRoomService(chatRepository)
	roomUsecase := chat3.NewRoomUsecase(createRoomService, chatRepository)
	chatServiceHandler := NewChatServiceHandler(roomUsecase)
	return chatServiceHandler
}
