// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package server

import (
	"database/sql"
	"github.com/uptrace/bun"
	"github.com/uptrace/bun/dialect/pgdialect"
	"github.com/uptrace/bun/driver/pgdriver"
	"net/http"
)

// Injectors from wire.go:

func initializeMemoHandler(db *bun.DB) *MemoHandler {
	memoRepository := NewMemoRepository(db)
	memoHandler := NewMemoHandler(memoRepository)
	return memoHandler
}

func initializeOIDCHandler(conf Config) *OIDCHandler {
	client := provideHttpClient()
	oidcHandler := NewOIDCHandler(conf, client)
	return oidcHandler
}

func InitDBConn(conf DBConfigIF) *bun.DB {
	db := provideOpenDB(conf)
	return db
}

// wire.go:

func provideHttpClient() *http.Client {
	return &http.Client{}
}

type DBConfigIF interface {
	DBDSN() string
}

func provideOpenDB(conf DBConfigIF) *bun.DB {
	sqldb := sql.OpenDB(pgdriver.NewConnector(pgdriver.WithDSN(conf.DBDSN())))
	db := bun.NewDB(sqldb, pgdialect.New())
	return db
}
